### ISSUE TITLE
Use webpack and babel-loader, @query is undefined

### ISSUE THREAD

**Issue by WUSO01** [lit/lit-element#1121] opened 2020-12-07 09:35 UTC
## Description
I wirted lit-element with typescript, i use webpack and babel compile my project. When i use babel-loader, `console.log(@query('xxx'))` is undefined, but i find ts-loader  won't occur this problem.

This is the minimalist demo:

**index.ts**:

```typescript
import { customElement, LitElement, html, query } from 'lit-element'

@customElement('custom-container')
export class CustomContainer extends LitElement {
  @query('#btn') btnEle: HTMLButtonElement

  firstUpdated () {
    console.log('this.btn is:', this.btnEle)
    this.btnEle.addEventListener('click', () => {
      console.log('click')
    })
  }

  render () {
    return html`
      <div>
        <button id="btn">button</button>
      </div>
    `
  }
}
```

**webapck.config.js**:

```javascript
module.exports = {
  // ...
  module: {
   rules: [
      {
        test: /\.ts?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          cacheDirectory: true,
          cacheCompression: false
        }
      }
    ]
  }
}
```
**babel.config.json**:

```json
{
  "presets": [
    "@babel/env",
    "@babel/preset-typescript"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators", {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties"
    ]
  ]
}
```

[Demo source file](https://github.com/WUSO01/query-babel-loader-issues)

The issues：

![image](https://user-images.githubusercontent.com/21070775/101334033-4ea98a00-38b2-11eb-8929-07a21fb16467.png)

**Comment by sorvell** [comment] 2020-12-10 20:07
Can you see if the decorator settings here work? This is what we use for testing: https://github.com/Polymer/lit-element/blob/master/.babelrc#L3.

If you'd like additional help debugging the issue, it'd be great if you could provide a minimal runnable reproduction. A simple github repo would be fine.

Hope that helps.

**Comment by sorvell** [comment] 2022-01-15 00:22
Closing due to age. Please open a new issue with a reproduction if the problem still exists. Thanks.

**Closed by sorvell** 2022-01-15 00:22 UTC
Labels: More Info Needed, Focus Area: Core Libraries
