### ISSUE TITLE
mixins don't work when using ESNext in tsconfig to compile

### ISSUE THREAD

**Issue by ByungHakNoh** [lit/lit-element#1180] opened 2021-03-30 15:09 UTC
## Description

There was no problem when I use commonJS to bundle my lit project. 
However, when I use ESNext, the bundling process is ok, but my page won't stop loading.
I found out what causes the loading problem..... when I change props in mixin it causes the problem. Am I wrong to use mixin like this?

- tsconfig.json

```javascript
"target": "ES5"
"module": "ESNext"
"sourceMap": true
"outDir": "./dist" 
"rootDir": "./src"
"strict": true
"moduleResolution": "node"
"esModuleInterop": true
"experimentalDecorators": true
"skipLibCheck": true
"forceConsistentCasingInFileNames": true
```

- mixin
```javascript
export const PendingContainer = <TBase extends AnyConstructor<LitElement>>(Base: TBase) => {
  class Mixin extends Base {
    @property({ type: Boolean }) hasPendingChildren = false

    constructor(...args: any[]) {
      super()
      let pendingCount = 0
      this.addEventListener('pending-state', async (e: Event) => {
        e.preventDefault()
        const detail = e as MutableObject
        pendingCount++
        this.hasPendingChildren = true
        await detail.promise
        pendingCount--
        this.hasPendingChildren = pendingCount != 0 // this line caused the problem. when i delete this it works find
      })
    }
  }
  return Mixin
}
```

## Acceptance criteria
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.

**Comment by sorvell** [comment] 2022-01-15 00:12
Closing due to age. If you're still having a problem with this, please post a reproduction using the [lit.dev/playground](https://lit.dev/playground/). Thanks.

**Closed by sorvell** 2022-01-15 00:12 UTC
Labels: Focus Area: Core Libraries
